### ISSUE TITLE
`query.config()`, used by Nezu in `_partials/common.j2`, isn't documented

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#18]
I can roughly figure out what's happening from Nezu's `README.md`, but maybe the mechanism is worth documenting somewhere?

On a related note: I had somehow missed the whole "Assets" thing. I'm not quite sure what they're really for, but... Interesting! And an Asset can be a Jinja template...? Intriguing!

**Comment by lepture** [comment]
I've added documentation in https://docs.typlog.com/en/article/design-template/ for `query.config`.

Maybe I should call "Asset" as "Raw"?

**Comment by michaellenaghan** [comment]
I don't think "Raw" is better. And "Asset" isn't completely wrong; the only issue is that the assets you can add today are a subset of what people usually think of — e.g., no fonts or images. But, hey, maybe someday you'll be able to add those too.

I'm still trying to understand the use case. Maybe here's one? 

I was talking about putting text in the footer. I assumed I'd have to use HTML injection if the text wasn't hard-coded in the template. In fact, it looks like I could actually create the structure of the footer in the template, and create a Markdown asset with a well-known name, and look for it in the template to get the text...

With a Markdown asset would I get Markdown text back from `query.config()`, or HTML? If it's Markdown, what Jinja filter would I use to convert it into HTML?

**Comment by michaellenaghan** [comment]
I think this is fully resolved; closing.
