### ISSUE TITLE
Not all logos are square, and some (maybe most?) logos include the site name

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#19]
This isn't an issue for me — I plan to change or create a theme anyway — but I think it's one more thing that affects "first impressions."

Typlog suggests a square logo, and then positions the logo beside the site name. There are people like me who have existing logos, and they aren't square. Not just that — I'd say that most logos include the site (i.e., brand) name; only very large and well-known brands can get away with logos that are only symbols. (And even those brands always *start* with names; they only drop the names once they become well-known.) 

Btw, if you agree with that, note the implication: in Western languages logos are almost always rectangular, not square, because they include words.

When I added my logo to the site, it ended up looking like this in Nezu:

<img width="444" alt="Screenshot 2022-11-09 at 11 10 09 AM" src="https://user-images.githubusercontent.com/176481/200882899-4491d68a-134e-4dc4-93a5-dc3f70f7f210.png">

That is... not good. :-) Even Ueno looks awkward:

<img width="286" alt="Screenshot 2022-11-09 at 11 08 03 AM" src="https://user-images.githubusercontent.com/176481/200883423-bcddf8d0-8d15-4ca0-a693-c35c1d5de12e.png">

At that point, unless I'm willing and able to modify the theme, I have only one choice: drop the use of the logo. (I can't drop the site name because it's required and used in places the logo isn't.)

I still have a Ghost trial site, and I checked to see what they do. It seems that in all of their themes they use the site name if there's no logo:

<img width="208" alt="Screenshot 2022-11-09 at 10 57 35 AM" src="https://user-images.githubusercontent.com/176481/200883590-4e0010ec-bc25-4991-80b1-5c38def80e9a.png">

and replace the site name with the logo if you supply it:

<img width="183" alt="Screenshot 2022-11-09 at 10 55 57 AM" src="https://user-images.githubusercontent.com/176481/200883689-2440d6eb-3244-4322-b58e-d3de7a3dff9e.png">

(Those are screenshots from one theme, Journal, but I tried more than one, and they all did that.)

I also took a quick look at the theme previews on Weebly, and it looks like they do the same thing. Name or logo, never both.

Although Typlog makes beautiful use of square logos, I think Ghost's approach is more likely to yield the correct result for most people most of the time.

P.S. "...most logos include the site name..." If a site — i.e., a brand — has an identity, that identity will include a specific typeface. That's why the logo would include the site/brand name.

**Comment by michaellenaghan** [comment]
I forgot to mention that the admin is affected by the same issue.

Here's what it looks like if I force the logo to be square:

<img width="220" alt="Screenshot 2022-11-09 at 11 06 43 AM" src="https://user-images.githubusercontent.com/176481/200916863-730b85cc-6804-47f0-8958-f3679cbdcce3.png">

Here's what it looks like if I use the logo in its default dimensions:

<img width="220" alt="Screenshot 2022-11-09 at 1 54 45 PM" src="https://user-images.githubusercontent.com/176481/200917089-faad13f0-9200-48c5-ab35-a6745e2c350f.png">

I think the admin should also use the name or the logo, but not both.

P.S. I assume Site IDs aren't secret...?

**Comment by lepture** [comment]
This is a mistake I made long ago. I've fixed it now with:

1. site.logo can be icon with text
2. site.icon should be squared icon

I'll need to update all the themes to match the updates.

**Comment by michaellenaghan** [comment]
Excellent solution. 

I think it would be worth doing one of these two things at the same time:

* Make light/dark toggling a feature that can itself be toggled in the admin

* Add dark mode icons and logos to the admin

Here's why.

At least two themes — including the default theme — allow *end-users* to toggle the light/dark mode in the browser. Without one of the two things I suggested many*** of your customers would almost certainly need to be Pro subscribers to get a good dark mode result. (They'd need Pro to either remove the light/dark toggle or use a Nezu-like mechanism for a dark mode logo. Both of those require not just Pro but also technical skill.) For built-in themes, that isn't good.

***Many? Well: those who a) have a logo that b) doesn't look good in dark mode. Probably not many. Some? But, really, it's the new user experience I keep focusing on.

===

One other thought. 

Existing customers will be affected by this if they switch to another template and then switch back.

That isn't specific to this particular change; it's just a result of the way Typlog handles themes. But this change will have a more visible effect than most.

Maybe they could get back to where they were by moving their logo to the icon slot? I'm not sure; it depends on how the themes actually use those things.

Just thinking about backwards compatibility...

**Comment by lepture** [comment]
FYI,

1. ueno and nezu supported dark mode in recent versions. There were no dark mode before.
2. I had taken the backwards compatibility into account when changing the code. Also, I've copied the logo to icon in database. People can now upload a different logo. But I have to update other themes to match the changes.

**Comment by michaellenaghan** [comment]
Understood.

One other thought, based on the new "use your own theme" feature: if users could optionally choose the version of a theme from the registry they'd always be able to go back to what they were using before.

I don't know if that's actually worthwhile. On the one hand, they'd have to understand versioning, and they'd have to know what version to go back to. On the other hand, your underlying implementation already supports the ability to choose a version; it's really just a UI issue. Maybe it's worth considering if there are certain kinds of breaking changes down the road?

**Comment by michaellenaghan** [comment]
On the account page there's a list of sites; it looks like that needs to be switched from logo to icon too:

<img width="188" alt="Screenshot 2022-11-14 at 11 57 03 AM" src="https://user-images.githubusercontent.com/176481/201720223-48630e4c-a456-4e0b-bfd3-5b341edd8466.png">

**Comment by michaellenaghan** [comment]
And in the account centre there's also My Sites:

<img width="267" alt="Screenshot 2022-11-15 at 12 05 26 PM" src="https://user-images.githubusercontent.com/176481/202266978-abf54187-beee-43b8-8c3c-00f605343599.png">

**Comment by lepture** [comment]
I think it is resolved. Please check the account page again.

**Comment by michaellenaghan** [comment]
There's still one more spot. 

My Sites...

<img width="200" alt="Screenshot 2022-11-21 at 11 10 11 AM" src="https://user-images.githubusercontent.com/176481/203103920-5368cc5b-447f-4eb7-809a-7a54a8db7ebb.png">

...isn't using the icon yet:

<img width="156" alt="Screenshot 2022-11-21 at 11 10 29 AM" src="https://user-images.githubusercontent.com/176481/203104114-0128550f-9a26-4ed5-b8bd-5763d3593b91.png">

**Comment by lepture** [comment]
fixed.
