### ISSUE TITLE
Some things used by themes aren't documented

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#20]
The following aren't documented [here](https://docs.typlog.com/en/article/design-template/):

* `_snippets/page_qr.j2` (used by theme Ginza)
* `_snippets/theme_toggle.j2` (used by theme Nezu & theme Ueno)
* `block foot_html` (used by theme Nezu)
* `block lang` (used by theme Akasaka)
* `features.foot_html`  (used by theme Nezu)
* `features.head_html`  (used by theme Akasaka & theme Meguro)

(I can figure out from context what they do, so this isn't a problem; I'm just letting you know.)

**Comment by lepture** [comment]
Hi @michaellenaghan 

I've added those **block** and **features** into documentation.

`_snippets/` are not suggested to use. I've just replaced `_snippets/theme_toggle.j2` in nezu:

https://github.com/typlog/nezu/commit/4a6d5ccdbfd8060cec961110aa0f352875cf56ef#diff-7d9e11e5f7e5e103a53a0d4fc4e6517b43e61e9baf1bcb4098cca6110dc33bceL47
