### ISSUE TITLE
Consider making the secondary color for new sites white

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#21]
Ueno and Nezu both use the secondary color defined in the admin to (among other things) color the links when you hover over them in dark mode.

I had to trace through the CSS to figure that out. :-)

Since Ueno is the default theme, maybe new sites should use white as the default secondary color? Right now the default secondary color is black, which means that links turn black when you hover over them in dark mode.

**Comment by lepture** [comment]
done
