### ISSUE TITLE
"Use your own theme" seems to be stuck at the initial version of the theme

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#22]
Nezu hides logos on small screens. I made a change to show it on small screens in my modified version, and tagged it 0.2.0; you can see all of that [here](https://github.com/michaellenaghan/nezu/compare/0.1.0...0.2.0).

The logo is showing up with `serve-theme`:

<img width="331" alt="Screenshot 2022-11-11 at 1 27 42 PM" src="https://user-images.githubusercontent.com/176481/201405682-9775be8f-12d4-4ce0-a99e-adca26a59df9.png">

but not on the site:

<img width="329" alt="Screenshot 2022-11-11 at 1 28 03 PM" src="https://user-images.githubusercontent.com/176481/201405788-200abfe3-917a-4862-89c1-e0fc88e95931.png">

despite the fact that it's selected in the admin:

<img width="542" alt="Screenshot 2022-11-11 at 1 28 57 PM" src="https://user-images.githubusercontent.com/176481/201406083-db37a1e1-bf39-4af6-a19c-d3bd465890b6.png">

(I even tried switching to a different theme and then back to my theme @ 0.2.0.)

**Comment by lepture** [comment]
Hi, you will have to update `version` in `theme.json` to match the tag. Your current `theme.json` is always pointing to `0.1.0`.

**Comment by michaellenaghan** [comment]
!!!

Sorry; thank you. I thought those fields were just meant to form the ”path,” and since I was passing the “path“ explicitly…  Oops.
