### ISSUE TITLE
How do you use Featured?

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#24]
Posts have a "Featured" flag:

<img width="310" alt="Screenshot 2022-11-11 at 3 58 50 PM" src="https://user-images.githubusercontent.com/176481/201430241-9f2282ef-446e-480a-93ff-aaaf780ba238.png">

I couldn't spot anything in the docs related to it, and the themes I tried didn't seem to do anything special with a Featured post.

Is "Featured" the same as "Protected Posts" in the pricing table?

<img width="635" alt="Screenshot 2022-11-11 at 4 01 37 PM" src="https://user-images.githubusercontent.com/176481/201430433-b89d9483-a57e-4ca1-9bc1-eaba06f0ac6f.png">

I also see a `.protected` CSS class in Nezu, but it doesn't seem to be used by any of Nezu's templates? (It could be used by one of the `render` macros Nezu calls though.)

**Comment by michaellenaghan** [comment]
It looks like `query` has a `featured_subjects` method?

And I don't see a `featured` property in `page`?

**Comment by lepture** [comment]
@michaellenaghan yes, there is no `featured` property on `page`. This is designed for showing your featured items at the top of your home page. Here is an example: https://themes.typlog.com/#/aoyama

**Comment by michaellenaghan** [comment]
OK, thank you; `featured_subjects`, used in Aoyama [here](https://github.com/jessuni/typlog-aoyama/blob/794b733c82d7bf890fcd516f2fe1a68aaef2371c/home.j2#L88), isn't documented [here](https://docs.typlog.com/en/article/design-template/).

I can add some documentation this week?

Here's why I was looking for a `featured` property on `page`: I wanted to avoid showing the same post twice.

That's actually happening in Aoyama: the featured Elements post appears twice. In fact, the second appearance is *right after* the first. That's exactly what I wanted to avoid. :-)

In Aoyama the duplication doesn't look bad, because the featured post is presented very differently. I wasn't thinking of doing that, so without filtering the duplication *would* look bad — like an error.

I think I can build the data structure I need using `featured_subjects`.

**Comment by lepture** [comment]
Actually you can filter the featured posts with:

```
{% posts = query.featured_subjects() %}
{% post_ids = {p.id for p in posts} %}

then you can filter with

{% if item.id not in post_ids %}
```

**Comment by michaellenaghan** [comment]
Yes, a dict keyed on `id` is what I meant by "build the data structure I need."

I'll close this...
