### ISSUE TITLE
GDPR doesn't allow the use of cookies without consent

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#25]
Typlog seems to store cookies in the browser when anonymous users browse sites. That very likely means that Typlog's users (i.e., Typlog's customers) are in violation of the GDPR.

I found a reasonable explanation of the issue [here](https://www.cookiebot.com/en/gdpr-cookies/); here's a relevant sampling:

> The GDPR requires a website to only collect personal data from users after they have given their explicit consent to the specific purposes of its use.
>
> Websites must comply with the following GDPR cookie requirements:
>
> * Prior and explicit consent must be obtained before any activation of cookies (apart from whitelisted, necessary cookies).
> ...

California has vaguely similar rules that are described [here](https://www.cookiebot.com/en/what-is-ccpa/).

It's possible that the cookies are just an oversight, and Typlog doesn't actually need them at all. If that's true, they should be removed; there's nothing more to talk about! I suspect, however, that the cookies are needed for the built-in analytics. 

If that's the case, I think there are two broad options.

The first is that Typlog is able to make its analytics cookie-free; in that case, no consent is needed. (I guess? I don't know if there are other subtleties.)

The second is that Typlog isn't able to make its analytics cookie-free; in that case, Typlog would need to introduce a cookie consent mechanism.

Personally, I really, really, really hate cookie consent dialogs. I wouldn't want to use them on my site, so I'd strongly prefer a third option: the ability to turn off features that require them. (I'm specifically focusing on *anonymous* users here.)

Btw, for my own sites I generally use GDPR-aware analytics like [Plausible.io](https://plausible.io) that don't use cookies and don't require consent.

**Comment by lepture** [comment]
Oh, I forgot to remove the cookie things. It is now removed.
