### ISSUE TITLE
Using `serve-theme`, one session loads `typlog.css` and `typlog.js` while the other doesn't

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#27]
I have `serve-theme` running twice, in two separate windows, on two separate ports. They're running against the same site, and they're using the same token.

One `serve-theme` is using my modified Nezu theme. The other `serve-theme` is using a new theme I'm developing.

The session running the modified Nezu theme loads `typlog.css` and `typlog.js` successfully. The session running the new theme does not.

The problem with the session that isn't working is the URLs.

Here's the HTML from the session that's running successfully:

```html
<link rel="stylesheet" href="https://s.typlog.com/ui/20221120-81da3ab8/typlog.css">
...
<script src="https://s.typlog.com/ui/20221120-81da3ab8/typlog.js"></script>
```

Here's the HTML from the session that isn't:

```html
<link rel="stylesheet" href="typlog.css">
...
<script src="typlog.js"></script>
```

I don't generate the HTML in either case, so I'm not sure why they're different.

I've tried things like stopping and re-starting the sessions, but so far nothing has made a difference. One session always works; the other one never does.

The only difference, I think, is that the modified Nezu theme is on Github, while the new theme isn't (yet). I don't think that would affect `serve-theme` though? Other than that, I think everything is the same?

Any thoughts?

(Btw, I'm not blocked, I'm manually loading the CSS and JS files in the meantime.)

**Comment by lepture** [comment]
@michaellenaghan I guess, there is a `config` variable in your theme. I've renamed our internal `config` variable to another name which would never be used by theme developers.

**Comment by michaellenaghan** [comment]
Brilliant, thank you!
