### ISSUE TITLE
Typlog 在 Moments 页面，点击图片有缩放比例不正确的 Bug

### ISSUE THREAD

**Issue by aiokr** [typlog/issues#3]
Typlog 在 Moments 页面，点击图片有缩放比例不正确的 Bug

环境是macOS 的 Safari 15，在微信内、小米手机自带浏览器也能复现。

https://user-images.githubusercontent.com/25877104/136894638-ab7dd86f-bb47-4836-b13e-3e2c2d0225c9.mov

**Comment by lepture** [comment]
@aiokr fixed. Thanks for your report.
