### ISSUE TITLE
Adding primary and secondary links doesn't work as expected

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#7]
Here's what I did:

* I set the title of the first primary link to About
* I set the URL of the first primary link to /about/
* I clicked Update

Then I went to the site... and the link wasn't there.

I went back to the Settings page, refreshed it, and my first primary link disappeared.

Hmmm.

I repeated the entire sequence... and the link still wasn't there.

I then did this:

* I set the title of the first primary link to About
* I set the URL of the first primary link to /about/
* I clicked +
* I clicked Update

Then I went back to the site, forced a page refresh, and the link showed up.

It's not obvious that you always need an empty row?

**Comment by lepture** [comment]
This has been fixed. Thanks for your feedback.
