### ISSUE TITLE
The Pages page shows the wrong URL

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#8]
I changed the route for pages to `/{slug}/` — note the trailing slash.

It's shown correctly in the page's metadata:

<img width="320" alt="Screenshot 2022-11-07 at 1 19 22 PM" src="https://user-images.githubusercontent.com/176481/200385609-96df25dd-748a-4a3e-aeab-d3e654c34eda.png">

but not on the Pages page:

<img width="132" alt="Screenshot 2022-11-07 at 1 18 51 PM" src="https://user-images.githubusercontent.com/176481/200385674-2a6b80c8-ec0c-45ea-a881-2425308763af.png">

**Comment by lepture** [comment]
This has been fixed. Thanks for your feedback.
